### ISSUE TITLE
How can I pass parameters to translation helper?

### ISSUE THREAD

**Issue by itrich** [vazco/universe-i18n-blaze#2]
Hi all,

I'm trying to translate an Blaze powered application with the help of universe:i18n and universe:i18n-blaze. While this works perfectly for simple strings, I'm stuck at translating parametrized strings, e.g. _"Showing {$visible} of {$all} entries."_

How can I pass a parameter (e.g. {{countVisible}} to a translation helper (e.g. {{__ 'counter'}}) within a Blaze template, whereas my translation file looks like this:

```
_locale: 'en-US'
_splitKey: '.'
counter: "Showing {$visible} of {$all} entries"  
```

**Comment by kestarumper** [comment]
Hi @itrich,

> How can I pass a parameter (e.g. {{countVisible}} to a translation helper (e.g. {{__ 'counter'}}) within a Blaze template, whereas my translation file looks like this:

You can do this by passing _keyword arguments_. Look at example [here](http://blazejs.org/api/templates.html#Template-helpers). In your case: 
```
{{__ 'counter' visible=countVisible all=countAll}}
```

**Comment by itrich** [comment]
Thank you for your answer, which works perfectly.

By the way, if someone finds this issue looking for a similar problem: The keys _locale and _purify can be passed to the translation helper exactly the same way. For instance, 

```{{__ 'counter' _purify='string => string' visible=countVisible all=countAll}}```

(note the position of _purify) enables the usage of HTML tags within the translatable string.
